/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        try {
            fileLinter();
        } catch (IOException e) {
            e.printStackTrace();
            System.out.println("error reading file");
        }
    }

    public static void fileLinter () throws FileNotFoundException {
        String fileA = "gates.js";
        File file = new File(fileA);
        Scanner scanner = new Scanner(file);
        String line = scanner.nextLine();
        System.out.println(line);
    }
}
