/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import static java.lang.Math.random;

public class Library {
    public boolean someLibraryMethod() {
//        int[] rollsArr = roll(3);
//        System.out.println(rollsArr[0]);
//        int tester = randomNumberOneToSix();
//        System.out.println(tester);
        return true;
    }

    //feature #1: roll dice and contain results in an array
    public static int[] roll(int n){
        int[] rolls = new int[n];
        for (int i =0; i < rolls.length; i++){
            rolls[i] = randomNumberOneToSix();
        }
        return rolls;
    }

    //this helper function makes testing easier
    public static int randomNumberOneToSix(){
        int num  = (int) Math.ceil(6 * Math.random());
        return num;
    }

    //detect duplicates
    public static boolean containsDuplicates(int[] results){
        for (int i = 0; i < results.length; i++) {
            int value = results[i];
            for (int j = 0; j < results.length; j++) {
                if (i != j && results[j] == value) {
                    return true;
                }
            }
        }

        return false;
    }

}
