/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import static java.lang.Math.random;

public class Library {
    public boolean someLibraryMethod () {
        return true;
    }

    //feature #1: roll dice and contain results in an array
    public static int[] roll (int n) {
        int[] rolls = new int[n];
        for (int i =0; i < rolls.length; i++){
            rolls[i] = randomNumberOneToSix();
        }
        return rolls;
    }

    //this helper function makes testing easier
    public static int randomNumberOneToSix () {
        int num  = (int) Math.ceil(6 * Math.random());
        return num;
    }

    //detect duplicates
    public static boolean containsDuplicates (int[] results) {
        for (int i = 0; i < results.length; i++) {
            int value = results[i];
            for (int j = 0; j < results.length; j++) {
                if (i != j && results[j] == value) {
                    return true;
                }
            }
        }
        return false;
    }

    //calculate averages
    public static int calculateAverage (int[] intArr) {
        if(intArr.length == 0){
            return 0;
        }
        int sum = 0;
        for (int element : intArr) {
            sum += element;
        }
        sum = sum / intArr.length;
        return sum;
    }

    //Array of Arrays
    public static int[] lowestAverage (int[][] intArr) {
        int[] lowestAverageArray = intArr[0];
        for (int[] subArray : intArr) {
            if (calculateAverage(subArray) < calculateAverage(lowestAverageArray)) {
                lowestAverageArray = subArray;
            }
        }
        return lowestAverageArray;
    }
}
